export const showcases = [
  {
    slug: 'publishing-flow', kicker: 'Process flow',
    description: 'A compact declarative publishing pipeline with source-linked entities.',
    layout: { direction: 'LR', spacing: 44, layerSpacing: 82, padding: 32 },
    graph: {
      id: 'publishing-flow', title: 'Declarative publishing flow',
      description: 'Source is validated, laid out, rendered, and published as a self-contained artifact.',
      nodes: [
        { id: 'source', type: 'document', label: 'Declarative source', source: { file: 'publish.rcl', line: 12, path: 'DATA-DIVISION' } },
        { id: 'validate', type: 'process', label: 'Validate intent', source: { file: 'publish.rcl', line: 28, path: 'VALIDATE' } },
        { id: 'layout', type: 'process', label: 'Derive layout', source: { file: 'publish.rcl', line: 34, path: 'LAYOUT' } },
        { id: 'render', type: 'process', label: 'Render artifact', source: { file: 'publish.rcl', line: 41, path: 'RENDER' } },
        { id: 'artifact', type: 'document', label: 'Self-contained artifact', status: 'healthy', source: { file: 'publish.rcl', line: 48, path: 'OUTPUT' } },
      ],
      edges: [
        { from: 'source', to: 'validate', type: 'flow' }, { from: 'validate', to: 'layout', type: 'flow' },
        { from: 'layout', to: 'render', type: 'flow' }, { from: 'render', to: 'artifact', type: 'flow' },
      ],
    },
  },
  {
    slug: 'release-decision', kicker: 'Decision flow',
    description: 'A branching release gate demonstrating labels, decisions, and recovery paths.',
    layout: { direction: 'TB', spacing: 52, layerSpacing: 68, padding: 32 },
    graph: {
      id: 'release-decision', title: 'Release readiness decision',
      description: 'A release candidate proceeds only when quality and accessibility gates pass.',
      nodes: [
        { id: 'candidate', type: 'document', label: 'Release candidate', source: { file: 'release.rcl', line: 8 } },
        { id: 'quality', type: 'decision', label: 'Quality gates pass?', source: { file: 'release.rcl', line: 19 } },
        { id: 'accessibility', type: 'decision', label: 'Accessibility verified?', source: { file: 'release.rcl', line: 27 } },
        { id: 'publish', type: 'process', label: 'Publish release', status: 'healthy', source: { file: 'release.rcl', line: 36 } },
        { id: 'revise', type: 'process', label: 'Revise implementation', status: 'warning', source: { file: 'release.rcl', line: 44 } },
      ],
      edges: [
        { from: 'candidate', to: 'quality', type: 'flow' }, { from: 'quality', to: 'accessibility', type: 'flow', label: 'Yes' },
        { from: 'quality', to: 'revise', type: 'error', label: 'No' }, { from: 'accessibility', to: 'publish', type: 'flow', label: 'Yes' },
        { from: 'accessibility', to: 'revise', type: 'error', label: 'No' },
      ],
    },
  },
  {
    slug: 'commerce-platform', kicker: 'Dependency map',
    description: 'A layered service map with typed relationships, status, and semantic groups.',
    layout: { direction: 'LR', spacing: 48, layerSpacing: 88, padding: 32 },
    graph: {
      id: 'commerce-platform', title: 'Commerce platform dependencies',
      description: 'A source-aware service dependency map for a commerce platform.',
      groups: [
        { id: 'experience', label: 'Experience layer' }, { id: 'services', label: 'Service layer' },
        { id: 'data', label: 'Data and events' }, { id: 'external', label: 'External systems' },
      ],
      nodes: [
        { id: 'storefront', type: 'service', label: 'Storefront', group: 'experience', status: 'healthy', source: { file: 'commerce.rcl', line: 21 } },
        { id: 'admin', type: 'service', label: 'Operations console', group: 'experience', source: { file: 'commerce.rcl', line: 27 } },
        { id: 'gateway', type: 'service', label: 'API gateway', group: 'services', source: { file: 'commerce.rcl', line: 36 } },
        { id: 'checkout', type: 'process', label: 'Checkout orchestration', group: 'services', source: { file: 'commerce.rcl', line: 43 } },
        { id: 'inventory', type: 'service', label: 'Inventory', group: 'services', status: 'warning', source: { file: 'commerce.rcl', line: 51 } },
        { id: 'orders', type: 'database', label: 'Order store', group: 'data', source: { file: 'commerce.rcl', line: 62 } },
        { id: 'events', type: 'queue', label: 'Commerce events', group: 'data', source: { file: 'commerce.rcl', line: 68 } },
        { id: 'payment', type: 'external', label: 'Payment provider', group: 'external', status: 'critical', source: { file: 'commerce.rcl', line: 77 } },
      ],
      edges: [
        { from: 'storefront', to: 'gateway', type: 'request' }, { from: 'admin', to: 'gateway', type: 'request' },
        { from: 'gateway', to: 'checkout', type: 'flow' }, { from: 'checkout', to: 'inventory', type: 'dependency', label: 'Reserve' },
        { from: 'checkout', to: 'orders', type: 'data', label: 'Persist' }, { from: 'checkout', to: 'events', type: 'event', label: 'Publish' },
        { id: 'authorize-payment', from: 'checkout', to: 'payment', type: 'error', label: 'Authorize' },
      ],
      annotations: [
        { id: 'inventory-risk', target: { kind: 'node', id: 'inventory' }, type: 'risk', severity: 'warning', label: 'Capacity risk', body: 'Reservation capacity can constrain checkout throughput.', source: { file: 'commerce.rcl', line: 54 } },
        { id: 'payment-boundary', target: { kind: 'edge', id: 'authorize-payment' }, type: 'constraint', severity: 'critical', label: 'Trust boundary', body: 'Authorization crosses into an external payment system.', source: { file: 'commerce.rcl', line: 81 } },
        { id: 'service-ownership', target: { kind: 'group', id: 'services' }, type: 'decision', label: 'Ownership', body: 'The commerce platform team owns orchestration and inventory behavior.', source: { file: 'commerce.rcl', line: 31 } },
        { id: 'checkout-evidence', target: { kind: 'node', id: 'checkout' }, type: 'evidence', label: 'Source evidence', body: 'The orchestration contract is declared in commerce.rcl.', source: { file: 'commerce.rcl', line: 43 } },
      ],
    },
  },
  {
    slug: 'trust-architecture', kicker: 'System architecture',
    description: 'A grouped trust architecture spanning nested application, data, and external boundaries.',
    layout: { direction: 'LR', spacing: 46, layerSpacing: 86, padding: 32 },
    graph: {
      id: 'trust-architecture', title: 'Source-aware trust architecture',
      description: 'Requests cross explicit trust boundaries while semantic identity survives the pipeline.',
      groups: [
        { id: 'platform', label: 'Platform' }, { id: 'application', label: 'Application', parent: 'platform' },
        { id: 'data', label: 'Protected data', parent: 'platform' }, { id: 'outside', label: 'External boundary' },
      ],
      nodes: [
        { id: 'user', type: 'actor', label: 'Authorized user', group: 'outside', source: { file: 'trust.rcl', line: 18 } },
        { id: 'identity', type: 'external', label: 'Identity provider', group: 'outside', source: { file: 'trust.rcl', line: 24 } },
        { id: 'edge', type: 'service', label: 'Policy gateway', group: 'application', status: 'healthy', source: { file: 'trust.rcl', line: 35 } },
        { id: 'api', type: 'service', label: 'Application API', group: 'application', source: { file: 'trust.rcl', line: 42 } },
        { id: 'audit', type: 'queue', label: 'Audit stream', group: 'data', source: { file: 'trust.rcl', line: 53 } },
        { id: 'records', type: 'database', label: 'Protected records', group: 'data', source: { file: 'trust.rcl', line: 59 } },
      ],
      edges: [
        { from: 'user', to: 'edge', type: 'request' }, { from: 'edge', to: 'identity', type: 'dependency', label: 'Verify' },
        { from: 'edge', to: 'api', type: 'flow', label: 'Authorize' }, { from: 'api', to: 'records', type: 'data' },
        { from: 'api', to: 'audit', type: 'event' },
      ],
    },
  },
  {
    slug: 'northwind-schema', kicker: 'Relational schema',
    description: 'The canonical Northwind database expressed as semantic tables, domains, and foreign-key relationships.',
    artifact: { version: '1.0', asOf: '2026-08-27' },
    layout: { direction: 'LR', spacing: 52, layerSpacing: 92, padding: 36 },
    graph: {
      id: 'northwind-schema', title: 'Northwind relational model',
      description: 'Thirteen tables form a commerce system spanning sales, catalog, fulfillment, organization, and customer segmentation.',
      groups: [
        { id: 'sales', label: 'Sales and customers', description: 'Customer accounts, orders, and line items.' },
        { id: 'catalog', label: 'Product catalog', description: 'Products, categories, and suppliers.' },
        { id: 'fulfillment', label: 'Fulfillment', description: 'Shipping providers used to dispatch orders.' },
        { id: 'organization', label: 'Organization and territories', description: 'Employees, reporting lines, regions, and territory assignments.' },
        { id: 'segmentation', label: 'Customer segmentation', description: 'Customer demographic categories and their assignments.' },
      ],
      nodes: [
        { id: 'customers', type: 'table', label: 'Customers', group: 'sales', description: 'Organizations that place orders.', value: 'PK CustomerID', metadata: { columns: 11, primaryKey: 'CustomerID' }, source: { file: 'northwind-schema.sql', line: 42, path: 'CREATE TABLE Customers' } },
        { id: 'orders', type: 'table', label: 'Orders', group: 'sales', description: 'Commercial orders placed by customers.', value: 'PK OrderID', metadata: { columns: 14, primaryKey: 'OrderID' }, source: { file: 'northwind-schema.sql', line: 91, path: 'CREATE TABLE Orders' } },
        { id: 'order-details', type: 'table', label: 'Order Details', group: 'sales', description: 'Products, quantities, prices, and discounts for an order.', value: 'PK OrderID + ProductID', metadata: { columns: 5, primaryKey: ['OrderID', 'ProductID'] }, source: { file: 'northwind-schema.sql', line: 126, path: 'CREATE TABLE Order Details' } },
        { id: 'products', type: 'table', label: 'Products', group: 'catalog', description: 'Sellable products and their inventory state.', value: 'PK ProductID', metadata: { columns: 10, primaryKey: 'ProductID' }, source: { file: 'northwind-schema.sql', line: 154, path: 'CREATE TABLE Products' } },
        { id: 'categories', type: 'table', label: 'Categories', group: 'catalog', description: 'Product classification and presentation data.', value: 'PK CategoryID', metadata: { columns: 4, primaryKey: 'CategoryID' }, source: { file: 'northwind-schema.sql', line: 181, path: 'CREATE TABLE Categories' } },
        { id: 'suppliers', type: 'table', label: 'Suppliers', group: 'catalog', description: 'Organizations that supply products.', value: 'PK SupplierID', metadata: { columns: 12, primaryKey: 'SupplierID' }, source: { file: 'northwind-schema.sql', line: 202, path: 'CREATE TABLE Suppliers' } },
        { id: 'shippers', type: 'table', label: 'Shippers', group: 'fulfillment', description: 'Carriers responsible for order delivery.', value: 'PK ShipperID', metadata: { columns: 3, primaryKey: 'ShipperID' }, source: { file: 'northwind-schema.sql', line: 234, path: 'CREATE TABLE Shippers' } },
        { id: 'employees', type: 'table', label: 'Employees', group: 'organization', description: 'Staff members who own orders and report to other employees.', value: 'PK EmployeeID', metadata: { columns: 18, primaryKey: 'EmployeeID' }, source: { file: 'northwind-schema.sql', line: 252, path: 'CREATE TABLE Employees' } },
        { id: 'employee-territories', type: 'table', label: 'Employee Territories', group: 'organization', description: 'Associates employees with sales territories.', value: 'PK EmployeeID + TerritoryID', metadata: { columns: 2, primaryKey: ['EmployeeID', 'TerritoryID'] }, source: { file: 'northwind-schema.sql', line: 293, path: 'CREATE TABLE EmployeeTerritories' } },
        { id: 'territories', type: 'table', label: 'Territories', group: 'organization', description: 'Sales territories belonging to a region.', value: 'PK TerritoryID', metadata: { columns: 3, primaryKey: 'TerritoryID' }, source: { file: 'northwind-schema.sql', line: 312, path: 'CREATE TABLE Territories' } },
        { id: 'region', type: 'table', label: 'Region', group: 'organization', description: 'Top-level geographic sales regions.', value: 'PK RegionID', metadata: { columns: 2, primaryKey: 'RegionID' }, source: { file: 'northwind-schema.sql', line: 332, path: 'CREATE TABLE Region' } },
        { id: 'customer-demographics', type: 'table', label: 'Customer Demographics', group: 'segmentation', description: 'Reusable descriptions of customer segments.', value: 'PK CustomerTypeID', metadata: { columns: 2, primaryKey: 'CustomerTypeID' }, source: { file: 'northwind-schema.sql', line: 349, path: 'CREATE TABLE CustomerDemographics' } },
        { id: 'customer-customer-demo', type: 'table', label: 'Customer Customer Demo', group: 'segmentation', description: 'Associates customers with demographic segments.', value: 'PK CustomerID + CustomerTypeID', metadata: { columns: 2, primaryKey: ['CustomerID', 'CustomerTypeID'] }, source: { file: 'northwind-schema.sql', line: 365, path: 'CREATE TABLE CustomerCustomerDemo' } },
      ],
      edges: [
        { from: 'customers', to: 'orders', type: 'foreign-key', label: 'places' },
        { from: 'employees', to: 'orders', type: 'foreign-key', label: 'owns' },
        { from: 'shippers', to: 'orders', type: 'foreign-key', label: 'ships via' },
        { from: 'orders', to: 'order-details', type: 'foreign-key', label: 'contains' },
        { from: 'products', to: 'order-details', type: 'foreign-key', label: 'ordered as' },
        { from: 'categories', to: 'products', type: 'foreign-key', label: 'classifies' },
        { from: 'suppliers', to: 'products', type: 'foreign-key', label: 'supplies' },
        { from: 'employees', to: 'employees', type: 'foreign-key', label: 'reports to' },
        { from: 'employees', to: 'employee-territories', type: 'foreign-key', label: 'assigned' },
        { from: 'territories', to: 'employee-territories', type: 'foreign-key', label: 'covered by' },
        { from: 'region', to: 'territories', type: 'foreign-key', label: 'contains' },
        { from: 'customers', to: 'customer-customer-demo', type: 'foreign-key', label: 'segmented as' },
        { from: 'customer-demographics', to: 'customer-customer-demo', type: 'foreign-key', label: 'categorizes' },
      ],
    },
  },
]
